<h2>Form test</h2>

<h3>empty-form</h3>

<form id="empty-form">
</form>


<h3>non-empty-form</h3>

<form id="non-empty-form">
    <textarea></textarea>
    <button>OK</button>
    <input type="button">
    <input type="checkbox">
    <input type="color">
    <input type="date">
    <input type="datetime">
    <input type="datetime-local">
    <input type="email">
    <input type="file">
    <input type="hidden">
    <!-- Image does not carry over a value to the server. -->
    <input type="image">
    <input type="month">
    <input type="number">
    <input type="password">
    <input type="radio">
    <input type="range">
    <input type="reset">
    <input type="search">
    <input type="submit">
    <input type="time">
    <input type="tel">
    <input type="text">
    <input type="time">
    <input type="url">
    <input type="week">
    <select>
        <optgroup label="Group 1">
            <option>Option 1.1</option>
        </optgroup>
        <optgroup label="Group 2">
            <option>Option 2.1</option>
            <option>Option 2.2</option>
        </optgroup>
        <optgroup label="Group 3" disabled>
            <option>Option 3.1</option>
            <option>Option 3.2</option>
            <option>Option 3.3</option>
        </optgroup>
    </select>
</form>


<h3>with-required-el-form</h3>

<form id="with-required-el-form" action="/unknown/page/d8b2b9ab84890c089d9754919e658518">
    <input type="button" value="Click">
    <div class="form-group">
        <input type="text" required>
        <textarea required></textarea>
    </div>
</form>


<h3>server-error-form</h3>

<form action="/module/localhost/test/error.json" id="server-error-form">
    <button>Send</button>
</form>


<h3>redirect-form</h3>

<form action="/module/localhost/test/redirect.json" id="redirect-form">
    <button>Send</button>
</form>


<h3>with-values-form</h3>

<form id="with-values-form">
    <input name="textBox" value="bar">
    <input type="checkbox" name="checkBox">
</form>

<script src="/module/localhost/test/form-test.js"></script>
