dist: xenial
sudo: required
language: php
#group: deprecated-2017Q4

php:
# - hhvm
  - 7.3
  # https://docs.travis-ci.com/user/languages/php/#Nightly-builds
  - nightly

matrix:
  allow_failures:
#    - php: hhvm
    - php: nightly
  fast_finish: true

addons:
  # versions are listed here https://downloads.mariadb.org/
  #mariadb: 10.1
#  mariadb: latest
  firefox: latest

services:
  # https://docs.travis-ci.com/user/database-setup/#mysql
  - mysql

env:
  - DISPLAY=:99

before_install:
  - "id && pwd && uname -a"
  #- "ip addr show && cat /etc/hosts"
  - php -m

install:
  # For testing operations with a block device:
  - "sudo mknod -m 0777 /tmp/block-dev-test b 125 1; sudo chown $(id -u):$(id -g) /tmp/block-dev-test"

  # To running Selenium && firefox, see https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - export DISPLAY=':99.0'
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

  # `node` means `latest stable Node.js release`
  - nvm install node
  - "node --version && npm install -g typescript@next && tsc --version"
  - "cd public && npm install && cd .."

  - "travis_retry composer selfupdate && composer --version"
  - composer config -g github-oauth.github.com ${COMPOSER_TOKEN} &> /dev/null
  # Use `--prefer-dist` to download an archive instead of downloading sources.
  - travis_retry composer install --no-interaction

before_script:
  - "mysql -uroot -e \"DROP DATABASE IF EXISTS test; CREATE DATABASE test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""

script:
  - bin/test
  - php test/lint.php

# https://docs.travis-ci.com/user/deployment/pages/
# deploy nightly builds
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN
#  keep-history: true
#  # Directory to push to GitHub Pages, relative to the current directory, defaults to the current directory (example: your_build_folder)
#  local-dir: test/result
#  # Optional, be verbose about internal steps, defaults to false.
#  verbose: false
#  on:
#    repo: morpho-os/morpho-os.github.io
#    branch: master





