language: php
php:
    - hhvm
    - nightly

services:
    - mysql

before_script:
    - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
    - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON test.* TO 'root'@'localhost' IDENTIFIED BY '';\""
    - "mysql -uroot -e \"FLUSH PRIVILEGES;\""

script:
    - composer selfupdate && composer install --dev
    - phpunit -c test/server/phpunit.xml --bootstrap test/server/bootstrap.php

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true
