language: php
sudo: required
dist: trusty
group: edge

php:
    - 7.1
    #- nightly
    #- hhvm

services:
    - mysql

# Build lifecycle, see https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle:
#  1. before_install
#  2. install
#  3. before_script
#  4. script
#  5. after_success or after_failure
#  6. OPTIONAL before_deploy
#  7. OPTIONAL deploy
#  8. OPTIONAL after_deploy
#  9. after_script

install:
    - nvm install node
    - "node --version && npm install typescript@next"

before_script:
    - "id && pwd && uname -a"
    - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
    - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON test.* TO 'root'@'localhost' IDENTIFIED BY '';\""
    - "mysql -uroot -e \"FLUSH PRIVILEGES;\""

script:
    - travis_retry composer selfupdate
    - travis_retry composer install
    - vendor/phpunit/phpunit/phpunit -c test/server/phpunit.xml --bootstrap test/server/bootstrap.php

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true
