sudo: enabled
dist: trusty

language: php

php:
# - hhvm
  - 7.1

matrix:
#  allow_failures:
#    - php: hhvm
  fast_finish: true

addons:
  # versions are listed here https://downloads.mariadb.org/
  mariadb: 10.1
  firefox: latest
  apt:
    packages:
      # For Selenium server.
      - oracle-java8-set-default

env:
  - DISPLAY=:99

# Build lifecycle, see https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle:
#  1. before_install
#  2. install
#  3. before_script
#  4. script
#  5. after_success or after_failure
#  6. OPTIONAL before_deploy
#  7. OPTIONAL deploy
#  8. OPTIONAL after_deploy
#  9. after_script

before_install:
  - "id && pwd && uname -a"
  #- "ip addr show && cat /etc/hosts"
  - php -m

install:
  # For testing operations with a block device:
  - "sudo mknod -m 0777 /tmp/block-dev-test b 125 1; sudo chown $(id -u):$(id -g) /tmp/block-dev-test"

  # To running Selenium && firefox, see https://docs.travis-ci.com/user/gui-and-headless-browsers/
  - export DISPLAY=':99.0'
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

    # `node` means `latest stable Node.js release`
  - nvm install node
  - "node --version && npm install -g typescript@next && tsc --version"
  - "cd public && npm install"

    # Composer
  - "travis_retry composer selfupdate && composer --version"
  - travis_retry composer install

before_script:
  - "mysql -uroot -e \"DROP DATABASE IF EXISTS test; CREATE DATABASE test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""

script:
  - bin/test