language: php
sudo: required
dist: trusty
group: edge

php:
    - 7.1
    #- nightly
    #- hhvm

addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

services:
    - mysql

# Build lifecycle, see https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle:
#  1. before_install
#  2. install
#  3. before_script
#  4. script
#  5. after_success or after_failure
#  6. OPTIONAL before_deploy
#  7. OPTIONAL deploy
#  8. OPTIONAL after_deploy
#  9. after_script

install:
    - "id && pwd && uname -a"
    # `node` means `latest stable Node.js release`
    - nvm install node
    - "node --version && npm install -g typescript@next && tsc --version"

before_script:
    - "mysql -uroot -e \"DROP DATABASE IF EXISTS test; CREATE DATABASE test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
    #- "mysql -uroot -e \"GRANT ALL PRIVILEGES ON test.* TO 'root'@'localhost' IDENTIFIED BY '';\""
    #- "mysql -uroot -e \"FLUSH PRIVILEGES;\""
    - travis_retry composer selfupdate
    - travis_retry composer install

script:
    - vendor/phpunit/phpunit/phpunit -c test/server/phpunit.xml --bootstrap test/server/bootstrap.php

matrix:
    allow_failures:
        - php: hhvm
    fast_finish: true
