language: php

php:
# - hhvm
  - 7.1

matrix:
#  allow_failures:
#    - php: hhvm
  fast_finish: true

addons:
  # versions are listed here https://downloads.mariadb.org/
  mariadb: 10.1

#If you require sudo, add 'sudo: required' to your .travis.yml

# Build lifecycle, see https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle:
#  1. before_install
#  2. install
#  3. before_script
#  4. script
#  5. after_success or after_failure
#  6. OPTIONAL before_deploy
#  7. OPTIONAL deploy
#  8. OPTIONAL after_deploy
#  9. after_script

before_install:
  - "id && pwd && uname -a"
  - php -m
  - ls -al /sys/block

install:
    # `node` means `latest stable Node.js release`
  - nvm install node
  - "node --version && npm install -g typescript@next && tsc --version"
  - travis_retry composer selfupdate
  - travis_retry composer install

before_script:
  - "mysql -uroot -e \"DROP DATABASE IF EXISTS test; CREATE DATABASE test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
#  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON test.* TO 'root'@'localhost' IDENTIFIED BY '';\""
#  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON test.* TO 'root'@'127.0.0.1' IDENTIFIED BY '';\""
#  - "mysql -uroot -e \"UPDATE mysql.user SET plugin='mysql_native_password'; FLUSH PRIVILEGES\""
#  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""

script:
  - bin/run-tests
#  - php -d pdo_mysql.default_socket=/run/mysql-5.6/mysqld.sock -f vendor/phpunit/phpunit/phpunit -- -c test/server/phpunit.xml
#  - php -d pdo_mysql.default_socket=/run/mysql-5.6/mysqld.sock -f test/server/db-connection-test.php
#  - php -f test/server/db-connection-test.php
