<form>
</form>

<form>
    <textarea></textarea>
    <button>OK</button>
    <input type="button">
    <input type="checkbox">
    <input type="color">
    <input type="date">
    <input type="datetime">
    <input type="datetime-local">
    <input type="email">
    <input type="file">
    <input type="hidden">
    <!-- Image does not carry over a value to the server. -->
    <input type="image">
    <input type="month">
    <input type="number">
    <input type="password">
    <input type="radio">
    <input type="range">
    <input type="reset">
    <input type="search">
    <input type="submit">
    <input type="time">
    <input type="tel">
    <input type="text">
    <input type="time">
    <input type="url">
    <input type="week">
    <select>
        <optgroup label="Group 1">
            <option>Option 1.1</option>
        </optgroup>
        <optgroup label="Group 2">
            <option>Option 2.1</option>
            <option>Option 2.2</option>
        </optgroup>
        <optgroup label="Group 3" disabled>
            <option>Option 3.1</option>
            <option>Option 3.2</option>
            <option>Option 3.3</option>
        </optgroup>
    </select>
</form>

<form>
    <input type="button">
    <input type="text" required>
    <textarea required></textarea>
</form>

<script src="/module/system/test/form-test.js"></script>
<script>
$(function () {
    define(["require", "exports", "system/lib/test-suite", "system/test/form-test"], function (require, exports, suite, module) {
        (new suite.TestSuite()).run(module.tests);
    });
});
</script>