<?php require __DIR__ . '/../_page-top.phtml' ?>
<link rel="stylesheet" type="text/css" href="/node_modules/jasmine-core/lib/jasmine-core/jasmine.css">
<?php require __DIR__ . '/../_main-menu.phtml' ?>
<div id="main-container" class="container">
    <?php /*
    <div id="taskbar">
        <a class="btn"><i class="fa fa-edit"></i></a>
    </div>
    */ ?>
    <div id="main-window">
        <div class="container" id="main-window-inner">
            <?php if (isset($this->pageTitle)): ?>
                <h1 id="page-header"><?= $this->pageTitle ?></h1>
            <?php endif ?>
            <?php print $this->messenger()->renderPageMessages() ?>
            <div id="page-body">
                <?php print $body ?>
            </div>
        </div>
    </div>
</div>
<?php require __DIR__ . '/../_script.phtml' ?>
<script type="text/javascript" src="/node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
<script type="text/javascript" src="/node_modules/jasmine-core/lib/jasmine-core/jasmine-html.js"></script>
<script type="text/javascript" src="/node_modules/jasmine-core/lib/jasmine-core/boot.js"></script>
<script src="/module/system/lib/check.js"></script>
<script>
jasmine.getEnv().addReporter({
    jasmineDone: function (runDetails) {
        if (window.location.search.indexOf('selenium') >= 0) {
            document.getElementById('page-body').innerHTML += '<h2 id="testing-results">' + runDetails.failedExpectations.length + '</h2>';
            //alert($('.jasmine_html-reporter .jasmine-alert .jasmine-passed').text())
        }
    }
});
</script>
</body>
</html>