<?php require __DIR__ . '/../../../bootstrap/view/_page-top.phtml' ?>
<?php require __DIR__ . '/../../../bootstrap/view/widget/main-menu.phtml' ?>
<div id="main-container" class="container">
    <?php /*
    <div id="taskbar">
        <a class="btn"><i class="fa fa-edit"></i></a>
    </div>
    */ ?>
    <div id="main-window">
        <div class="container" id="main-window-inner">
            <?php if (isset($this->pageTitle)): ?>
                <h1 id="page-header"><?= $this->pageTitle ?></h1>
            <?php endif ?>
            <?php print $this->messenger()->renderPageMessages() ?>
            <div id="page-body">
                <?php print $body ?>
            </div>
        </div>
    </div>
</div>
<script src="/node_modules/es5-shim/es5-shim.js"></script>
<script src="/node_modules/jquery/dist/jquery.js"></script>
<script src="/node_modules/bootstrap-styl/js/dropdown.js"></script>
<script src="/node_modules/bootstrap-styl/js/collapse.js"></script>
<script src="/node_modules/imd/imd.js"></script>
<script src="/module/system/lib/index.js"></script>
<script src="/module/system/lib/test-case.js"></script>
<script src="/module/system/lib/test-suite.js"></script>
</body>
</html>