<h1>Installation</h1>

<div>
    <form id="install-form" method="post" class="form-horizontal" action="/install">
        <fieldset>
            <legend>MySQL database configuration</legend>

            <div class="form-group">
                <label class="control-label col-lg-2">Database</label>

                <div class="col-lg-2">
                    <input type="text" name="db" class="form-control" id="db" required autofocus>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2">User</label>

                <div class="col-lg-2">
                    <input type="text" name="user" value="root" class="form-control" id="user" required>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-lg-2">Password</label>

                <div class="col-lg-2">
                    <input type="password" name="password" class="form-control" autocomplete="off" id="password">
                </div>
            </div>

            <div class="form-group" id="host-port-group">
                <label class="control-label col-lg-2">Host and Port</label>

                <div class="col-lg-2">
                    <input type="text" name="host" value="127.0.0.1" class="form-control" placeholder="host">
                </div>
                <div class="col-lg-1">
                    <input type="text" name="port" value="3306" class="form-control" placeholder="port">
                </div>
            </div>

            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                    <label class="checkbox-inline">
                        <input type="checkbox" name="dropTables" value="1" id="drop-tables"> Drop all tables in the
                        '<span id="target-db"></span>' database.
                    </label>
                </div>
            </div>

            <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                    <button type="submit" class="btn btn-default" style="margin-top: 1.5em; display: block;" id="install">
                        Install
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
</div>
<script>
$(function () {
    //'use strict';
    var __extends = (this && this.__extends) || function (d, b) {
            for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
            function __() { this.constructor = d; }
            d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
        };
    (function (System) {
        var Install;
        (function (Install) {
            var InstallForm = (function (_super) {
                __extends(InstallForm, _super);
                function InstallForm() {
                    _super.apply(this, arguments);
                }
                InstallForm.prototype.registerEventHandlers = function () {
                    var _this = this;
                    _super.prototype.registerEventHandlers.call(this);
                    this.getDbNameEl().on('keyup change blur', function () {
                        _this.setTargetDbElText(_this.getDbName());
                    });
                };
                InstallForm.prototype.getDbNameEl = function () {
                    return this.el.find('#db');
                };
                InstallForm.prototype.getDbName = function () {
                    return this.getDbNameEl().val();
                };
                InstallForm.prototype.setTargetDbElText = function (text) {
                    this.getTargetDbEl().text(text);
                };
                InstallForm.prototype.getTargetDbEl = function () {
                    return this.el.find('#target-db');
                };
                InstallForm.prototype.handleSuccessfulResponse = function (responseData) {
                    if (!responseData.redirect) {
                        alert('Invalid response was received');
                    }
                    else {
                        System.redirectToHome();
                    }
                };
                return InstallForm;
            })(System.Form);
            Install.InstallForm = InstallForm;
        })(Install = System.Install || (System.Install = {}));
    })(System || (System = {}));

    var form = new System.Install.InstallForm('#install-form');
});
</script>
