<?php require __DIR__ . '/../_top.phtml' ?>
<?php require __DIR__ . '/../_main-menu.phtml' ?>
<?php require __DIR__ . '/../_main.phtml' ?>
<?php require __DIR__ . '/../_script.phtml' ?>
<link rel="stylesheet" href="/localhost/rc/css/test.css">
<script src="/node_modules/jasmine-core/lib/jasmine-core/jasmine.js"></script>
<script src="/localhost/lib/test/jasmine.js"></script>
<script src="/localhost/lib/test/check.js"></script>
<script src="/localhost/test/index.js"></script>
<script>
define(["require", "exports", "localhost/test/index"], function (require, exports, module) {
    module.main();
});
</script>
</body>
</html>
