<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php
    //  <link rel="shortcut icon" href="../../assets/ico/favicon.png">
    ?>
    <title><?= $this->var()->pageTitle ?></title>
    <link href="/module/system/css/main.css" rel="stylesheet">
</head>
<body>

