<?php require __DIR__ . '/_page-top.phtml' ?>
<?php require __DIR__ . '/widget/main-menu.phtml' ?>
<div id="main-container" class="container">
    <?php /*
    <div id="taskbar">
        <a class="btn"><i class="fa fa-edit"></i></a>
    </div>
    */ ?>
    <div id="main-window">
        <div class="container" id="main-window-inner">
            <h1 id="page-header"><?= $this->var()->pageTitle ?></h1>
            <?php print $this->messenger()->renderPageMessages() ?>
            <div id="page-body">
                <?php print $body ?>
            </div>
        </div>
    </div>
</div>
<?php require __DIR__ . '/_page-bottom.phtml' ?>
