<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php
    //  <link rel="shortcut icon" href="../../assets/ico/favicon.png">
    ?>
    <title><?= $this->var()->pageTitle ?></title>
    <link href="/resource/bootstrap/css/main.css" rel="stylesheet">
</head>
<body>
<?php require __DIR__ . '/widget/main-menu.phtml' ?>
<div id="main-container" class="container">
    <?php /*
    <div id="taskbar">
        <a class="btn"><i class="fa fa-edit"></i></a>
    </div>
    */ ?>
    <div id="main-window">
        <div class="container" id="main-window-inner">
            <h1 id="page-header"><?= $this->var()->pageTitle ?></h1>
            <?php print $this->messenger()->renderPageMessages() ?>
            <div id="page-body">
                <?php print $body ?>
            </div>
        </div>
    </div>
</div>
<?php require __DIR__ . '/_page-bottom.phtml' ?>