<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php
    //  <link rel="shortcut icon" href="../../assets/ico/favicon.png">
    ?>
    <title>Installation</title>
    <link href="/resource/bootstrap/css/main.css" rel="stylesheet">
</head>
<body>
<?php require __DIR__ . '/widget/main-menu.phtml' ?>
<div class="container" id="main-container">
    <?php print $body ?>
</div>
<script src="/bower_components/es5-shim/es5-shim.js"></script>
<script src="/bower_components/jquery/dist/jquery.js"></script>
<script src="/resource/system/js/morpho.js"></script>
</body>
</html>
