<script src="/node_modules/jquery/dist/jquery.js"></script>
<script src="/node_modules/bootstrap-styl/js/dropdown.js"></script>
<script src="/node_modules/bootstrap-styl/js/collapse.js"></script>
<script src="/node_modules/imd/imd.js"></script>
<script src="/node_modules/tslib/tslib.es6.js"></script>
<script src="/module/localhost/lib/index.js"></script>
<script src="/module/localhost/app/main.js"></script>
