<form action="/system/module" method="post" class="form-horizontal w-?">
    <div class="form-group">
        <label class="control-label col-lg-3">Module class</label>

        <div class="col-lg-6">
            <input type="text" name="class" class="form-control" autofocus>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-3 col-lg-9">
            <label class="checkbox-inline">
                <input type="checkbox" name="enable" checked> Enable
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-3 col-lg-9">
            <label class="checkbox-inline">
                <input type="checkbox" name="isTheme"> Is theme
            </label>
        </div>
    </div>
    <div class="form-group" style="margin-top: 2em;">
        <div class="col-lg-offset-3 col-lg-9">
            <button class="btn btn-success">Create</button>
        </div>
    </div>
</form>
