<?php $this->pageTitle = 'New Module'; ?>
<form action="/system/module" method="post" id="new-module-form">
    <div class="form-group">
        <label for="module-name">Module name (or class)</label>
        <div>
            <input type="text" name="module[name]" class="form-control" id="module-name" required>
        </div>
    </div>
    <div class="form-group">
        <div class="checkbox">
            <label>
                <input type="checkbox" name="module[enable]" checked> Enable
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="checkbox">
            <label>
                <input type="checkbox" name="module[isTheme]"> Is theme
            </label>
        </div>
    </div>
    <div class="form-group">
        <label>Create directories/files:</label><br>
        <label><input type="checkbox" class="check-all"> Check all</label>
        <?php print $this->dirHierarchyRenderer($node->moduleDirHierarchy()); ?>
    </div>
    <div class="form-group submit-btns">
        <button class="btn btn-success">Create</button>
    </div>
</form>