<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-left">
            <?php //print $this->widget('Menu')->renderSystemMenu(); ?>
        </div>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Morpho</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="main-menu">
                    <li><a href="/system/page">Pages</a></li>
                    <li><a href="/system/module/list">Modules</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cache and index <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?= $this->uriWithRedirectToSelf('/system/cache/rebuild-routes') ?>">Rebuild routes</a></li>
                            <li><a href="<?= $this->uriWithRedirectToSelf('/system/cache/rebuild-events') ?>">Rebuild events</a></li>
                            <li><a href="<?= $this->uriWithRedirectToSelf('/system/cache/clear-all') ?>">Clear cache</a></li>
                        </ul>
                    </li>
                    <li><a href="/system/test">Tests</a></li>
                </ul>
                <?php //print $this->widget('Menu')->render('main'); ?>
            </div>
        </div>
    </div>
</nav>
