<script src="/node_modules/es6-promise/dist/es6-promise.auto.js"></script>
<script src="/node_modules/jquery/dist/jquery.js"></script>
<script src="/node_modules/bootstrap-styl/js/dropdown.js"></script>
<script src="/node_modules/bootstrap-styl/js/collapse.js"></script>
<script src="/node_modules/imd/imd.js"></script>
<script src="/module/system/lib/index.js"></script>
<script src="/module/system/app/main.js"></script>
