# https://github.com/srggrs/assign-one-project-github-action
#name: handle-issues
on:
  workflow_dispatch:
  issues:
    types: [opened, labeled]
#  pull_request:
#    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign new issues to a project
    steps:
      - name: Assign new issues
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: 'https://github.com/morpho-os/framework/projects/3'
          column_name: 'To do'