# Based on https://github.com/shivammathur/test-setup-php/blob/master/.github/workflows/workflow.yml
name: Main workflow
on:
  push:
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['7.4', '8.0']
    name: ${{ matrix.operating-system }}, php-${{ matrix.php-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          #extensions: mbstring, xdebug, pcov, intl, gd
          #ini-values: "post_max_size=256M, short_open_tag=On, date.timezone=UTC"
#      - name: Add Problem Matcher
#        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
#
#      - name: Test action side effects
#        run: php -r "if(strpos(@exec('git status'), 'nothing to commit') === false) {throw new Exception('Action has side effects');}"

      - name: Testing PHP version
        run: |
          php -v
          php -r "if(strpos(phpversion(), '${{ matrix.php-version }}') === false) {throw new Exception('Wrong PHP version Installed');}"

      - name: Run CI script
        run: .github/workflows/ci