# [GitHub Actions Documentation](https://help.github.com/en/actions)
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: [‘7.4’, ‘8.0’]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}

      - name: Testing PHP version
        run: |
          php -v
          which -a php
          php -r "if (strpos(phpversion(), '${{ matrix.php-version }}') === false) {throw new Exception('Wrong PHP version installed');}"
#      - name: Run CI script
#        run: .github/workflows/ci


