<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-left">
            <?php //print $this->widget('Menu')->renderSystemMenu(); ?>
        </div>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Morpho</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" id="main-menu">
                    <li><a href="/system/module/list">Modules</a></li>
                    <li><a href="<?= $this->uriWithRedirectToSelf('/system/module/rebuild-routes') ?>">Rebuild routes</a></li>
                    <li><a href="<?= $this->uriWithRedirectToSelf('/system/module/rebuild-events') ?>">Rebuild events</a></li>
                </ul>
                <?php //print $this->widget('Menu')->render('main'); ?>
            </div>
        </div>
    </div>
</nav>
